services:
  - type: web
    name: blog-system-flask
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn 'app:app'"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.6
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: blog-database
          property: connectionString

  - type: postgres
    name: blog-database
    plan: free